#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const protocolRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(protocolRoot, "../..");
const idlPath = resolve(protocolRoot, "idl/magic-context.json");
const idlText = await readFile(idlPath, "utf8");
const idl = JSON.parse(idlText);
const idlSha256 = createHash("sha256").update(idlText).digest("hex");
const checkOnly = process.argv.includes("--check");

const knownNames = new Set([
	...Object.keys(idl.enums),
	...Object.keys(idl.aliases),
	...Object.keys(idl.records),
	"ContextRuntimeCall",
	"ContextRuntimeResult",
]);

function json(value) {
	return JSON.stringify(value);
}

function fieldBase(field) {
	const { array: _array, map: _map, optional: _optional, ...base } = field;
	return base;
}

function schemaForSpec(spec) {
	if (spec.union) {
		return { oneOf: spec.union.map((name) => ({ $ref: `#/$defs/${name}` })) };
	}
	if (Array.isArray(spec.type)) {
		return {
			oneOf: spec.type.map((name) => schemaForSpec({ type: name })),
		};
	}
	if (spec.array) {
		const result = {
			type: "array",
			items: schemaForSpec(fieldBase(spec)),
		};
		if (spec.minItems !== undefined) result.minItems = spec.minItems;
		if (spec.maxItems !== undefined) result.maxItems = spec.maxItems;
		return result;
	}
	if (spec.map) {
		return {
			type: "object",
			additionalProperties: schemaForSpec(fieldBase(spec)),
		};
	}
	let result;
	if (spec.type === "json") result = {};
	else if (["string", "number", "integer", "boolean"].includes(spec.type)) {
		result = { type: spec.type };
	} else if (knownNames.has(spec.type)) {
		result = { $ref: `#/$defs/${spec.type}` };
	} else {
		throw new Error(`unknown IDL type ${String(spec.type)}`);
	}
	if (spec.const !== undefined) result.const = spec.const;
	for (const constraint of [
		"minimum",
		"maximum",
		"minLength",
		"maxLength",
		"pattern",
	]) {
		if (spec[constraint] !== undefined) result[constraint] = spec[constraint];
	}
	return result;
}

function buildSchema() {
	const defs = {};
	for (const [name, definition] of Object.entries(idl.enums)) {
		defs[name] = { type: "string", enum: definition.values };
	}
	for (const [name, definition] of Object.entries(idl.aliases)) {
		defs[name] = schemaForSpec(definition);
	}
	for (const [name, definition] of Object.entries(idl.records)) {
		const properties = {};
		const required = [];
		for (const [fieldName, field] of Object.entries(definition.fields)) {
			properties[fieldName] = schemaForSpec(field);
			if (!field.optional) required.push(fieldName);
		}
		defs[name] = {
			type: "object",
			additionalProperties: false,
			properties,
			required,
		};
	}
	defs.ContextRuntimeCall = {
		oneOf: Object.entries(idl.methods).map(([method, definition]) => ({
			type: "object",
			additionalProperties: false,
			properties: {
				method: { const: method },
				params: { $ref: `#/$defs/${definition.params}` },
			},
			required: ["method", "params"],
		})),
	};
	defs.ContextRuntimeResult = {
		oneOf: [
			...new Set(Object.values(idl.methods).map((definition) => definition.result)),
		].map((name) => ({ $ref: `#/$defs/${name}` })),
	};
	return {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		$id: idl.schemaId,
		title: idl.name,
		description:
			"Generated Magic Context runtime call schema. Edit idl/magic-context.json, never this file.",
		"x-protocol-version": idl.version,
		"x-idl-sha256": idlSha256,
		"x-method-results": Object.fromEntries(
			Object.entries(idl.methods).map(([method, definition]) => [
				method,
				definition.result,
			]),
		),
		$ref: "#/$defs/ContextRuntimeCall",
		$defs: defs,
	};
}

function tsType(spec) {
	let type;
	if (spec.const !== undefined) type = json(spec.const);
	else if (spec.union) type = spec.union.join(" | ");
	else if (Array.isArray(spec.type)) type = spec.type.join(" | ");
	else if (spec.type === "string") type = "string";
	else if (spec.type === "number" || spec.type === "integer") type = "number";
	else if (spec.type === "boolean") type = "boolean";
	else if (spec.type === "json") type = "unknown";
	else type = spec.type;
	if (spec.map) type = `Record<string, ${type}>`;
	if (spec.array) type = `Array<${type.includes(" | ") ? `(${type})` : type}>`;
	return type;
}

function generateTypeScript() {
	const lines = [
		"// @generated by plugin/protocol/scripts/generate.mjs; DO NOT EDIT.",
		`export const CORE_PROTOCOL_VERSION = ${idl.version} as const;`,
		`export const PROTOCOL_IDL_SHA256 = ${json(idlSha256)} as const;`,
		"",
	];
	for (const [name, definition] of Object.entries(idl.enums)) {
		if (definition.constName) {
			lines.push(
				`export const ${definition.constName} = ${JSON.stringify(definition.values)} as const;`,
				`export type ${name} = (typeof ${definition.constName})[number];`,
			);
		} else {
			lines.push(
				`export type ${name} = ${definition.values.map(json).join(" | ")};`,
			);
		}
		lines.push("");
	}
	for (const [name, definition] of Object.entries(idl.aliases)) {
		lines.push(`export type ${name} = ${tsType(definition)};`, "");
	}
	for (const [name, definition] of Object.entries(idl.records)) {
		lines.push(`export interface ${name} {`);
		for (const [fieldName, field] of Object.entries(definition.fields)) {
			lines.push(`\t${fieldName}${field.optional ? "?" : ""}: ${tsType(field)};`);
		}
		lines.push("}", "");
	}
	lines.push("export type ContextRuntimeCall =");
	for (const [method, definition] of Object.entries(idl.methods)) {
		lines.push(
			`\t| { method: ${json(method)}; params: ${definition.params} }`,
		);
	}
	lines[lines.length - 1] += ";";
	lines.push("", "export type ContextRuntimeResult =");
	for (const resultName of new Set(
		Object.values(idl.methods).map((definition) => definition.result),
	)) {
		lines.push(`\t| ${resultName}`);
	}
	lines[lines.length - 1] += ";";
	lines.push(
		"",
		`export const RUNTIME_METHODS = ${JSON.stringify(idl.methods, null, 2)} as const;`,
		"",
		`const PROTOCOL_IDL = ${JSON.stringify(idl)} as const;`,
		"",
		"function isRecord(value: unknown): value is Record<string, unknown> {",
		"\treturn Boolean(value) && typeof value === \"object\" && !Array.isArray(value);",
		"}",
		"",
		"function validateSpec(spec: any, value: unknown): boolean {",
		"\tif (spec.union) return spec.union.some((name: string) => validateNamed(name, value));",
		"\tif (Array.isArray(spec.type)) return spec.type.some((name: string) => validateNamed(name, value));",
		"\tif (spec.array) {",
		"\t\tif (!Array.isArray(value)) return false;",
		"\t\tif (spec.minItems !== undefined && value.length < spec.minItems) return false;",
		"\t\tif (spec.maxItems !== undefined && value.length > spec.maxItems) return false;",
		"\t\tconst child = { ...spec, array: undefined, optional: undefined, minItems: undefined, maxItems: undefined };",
		"\t\treturn value.every((item) => validateSpec(child, item));",
		"\t}",
		"\tif (spec.map) {",
		"\t\tif (!isRecord(value)) return false;",
		"\t\tconst child = { ...spec, map: undefined, optional: undefined };",
		"\t\treturn Object.values(value).every((item) => validateSpec(child, item));",
		"\t}",
		"\tif (spec.const !== undefined && value !== spec.const) return false;",
		"\tlet valid = false;",
		"\tif (spec.type === \"json\") valid = true;",
		"\telse if (spec.type === \"string\") valid = typeof value === \"string\";",
		"\telse if (spec.type === \"number\") valid = typeof value === \"number\" && Number.isFinite(value);",
		"\telse if (spec.type === \"integer\") valid = Number.isInteger(value);",
		"\telse if (spec.type === \"boolean\") valid = typeof value === \"boolean\";",
		"\telse valid = validateNamed(spec.type, value);",
		"\tif (!valid) return false;",
		"\tif (typeof value === \"string\") {",
		"\t\tif (spec.minLength !== undefined && value.length < spec.minLength) return false;",
		"\t\tif (spec.maxLength !== undefined && value.length > spec.maxLength) return false;",
		"\t\tif (spec.pattern !== undefined && !new RegExp(spec.pattern).test(value)) return false;",
		"\t}",
		"\tif (typeof value === \"number\") {",
		"\t\tif (spec.minimum !== undefined && value < spec.minimum) return false;",
		"\t\tif (spec.maximum !== undefined && value > spec.maximum) return false;",
		"\t}",
		"\treturn true;",
		"}",
		"",
		"function validateNamed(name: string, value: unknown): boolean {",
		"\tconst enums = PROTOCOL_IDL.enums as Record<string, { values: readonly unknown[] }>;",
		"\tif (enums[name]) return enums[name].values.includes(value);",
		"\tconst aliases = PROTOCOL_IDL.aliases as Record<string, any>;",
		"\tif (aliases[name]) return validateSpec(aliases[name], value);",
		"\tif (name === \"ContextRuntimeCall\") return validateRuntimeCall(value);",
		"\tif (name === \"ContextRuntimeResult\") {",
		"\t\treturn Object.values(PROTOCOL_IDL.methods).some((method) => validateNamed(method.result, value));",
		"\t}",
		"\tconst record = (PROTOCOL_IDL.records as Record<string, any>)[name];",
		"\tif (!record || !isRecord(value)) return false;",
		"\tconst allowed = new Set(Object.keys(record.fields));",
		"\tif (Object.keys(value).some((key) => !allowed.has(key))) return false;",
		"\tfor (const [fieldName, field] of Object.entries(record.fields) as Array<[string, any]>) {",
		"\t\tif (!(fieldName in value)) { if (field.optional) continue; return false; }",
		"\t\tif (!validateSpec(field, value[fieldName])) return false;",
		"\t}",
		"\treturn true;",
		"}",
		"",
		"export function validateRuntimeCall(value: unknown): value is ContextRuntimeCall {",
		"\tif (!isRecord(value) || Object.keys(value).length !== 2 || typeof value.method !== \"string\" || !(\"params\" in value)) return false;",
		"\tconst method = (PROTOCOL_IDL.methods as Record<string, { params: string }>)[value.method];",
		"\treturn Boolean(method) && validateNamed(method.params, value.params);",
		"}",
		"",
		"export function validateRuntimeResult(methodName: string, value: unknown): value is ContextRuntimeResult {",
		"\tconst method = (PROTOCOL_IDL.methods as Record<string, { result: string }>)[methodName];",
		"\treturn Boolean(method) && validateNamed(method.result, value);",
		"}",
		"",
	);
	return `${lines.join("\n")}\n`;
}

function pythonType(spec) {
	let type;
	if (spec.const !== undefined) type = `Literal[${JSON.stringify(spec.const)}]`;
	else if (spec.union) type = spec.union.join(" | ");
	else if (Array.isArray(spec.type)) type = spec.type.join(" | ");
	else if (spec.type === "string") type = "str";
	else if (spec.type === "number") type = "float";
	else if (spec.type === "integer") type = "int";
	else if (spec.type === "boolean") type = "bool";
	else if (spec.type === "json") type = "Any";
	else type = spec.type;
	if (spec.map) type = `dict[str, ${type}]`;
	if (spec.array) type = `list[${type}]`;
	return type;
}

function methodClassName(method) {
	return `${method
		.split(/[^A-Za-z0-9]+/)
		.map((part) => part[0].toUpperCase() + part.slice(1))
		.join("")}Call`;
}

function generatePython() {
	const lines = [
		'"""Generated Magic Context protocol bindings. Do not edit."""',
		"from __future__ import annotations",
		"",
		"import json",
		"from typing import Any, Literal, NotRequired, TypeAlias, TypedDict",
		"",
		`PROTOCOL_VERSION = ${idl.version}`,
		`PROTOCOL_IDL_SHA256 = ${json(idlSha256)}`,
		"",
	];
	for (const [name, definition] of Object.entries(idl.enums)) {
		if (definition.constName) {
			lines.push(
				`${definition.constName} = ${JSON.stringify(definition.values)}`,
			);
		}
		lines.push(
			`${name}: TypeAlias = Literal[${definition.values.map((value) => JSON.stringify(value)).join(", ")}]`,
			"",
		);
	}
	for (const [name, definition] of Object.entries(idl.records)) {
		lines.push(`class ${name}(TypedDict):`);
		for (const [fieldName, field] of Object.entries(definition.fields)) {
			const type = pythonType(field);
			lines.push(`    ${fieldName}: ${field.optional ? `NotRequired[${type}]` : type}`);
		}
		lines.push("");
	}
	for (const [name, definition] of Object.entries(idl.aliases)) {
		lines.push(`${name}: TypeAlias = ${pythonType(definition)}`, "");
	}
	const methodClasses = [];
	for (const [method, definition] of Object.entries(idl.methods)) {
		const className = methodClassName(method);
		methodClasses.push(className);
		lines.push(
			`class ${className}(TypedDict):`,
			`    method: Literal[${json(method)}]`,
			`    params: ${definition.params}`,
			"",
		);
	}
	lines.push(
		`ContextRuntimeCall: TypeAlias = ${methodClasses.join(" | ")}`,
		`ContextRuntimeResult: TypeAlias = ${[
			...new Set(Object.values(idl.methods).map((definition) => definition.result)),
		].join(" | ")}`,
		`RUNTIME_METHODS = ${JSON.stringify(idl.methods)}`,
		`_PROTOCOL_IDL = json.loads(${JSON.stringify(JSON.stringify(idl))})`,
		"",
		"def _validate_spec(spec: dict[str, Any], value: Any) -> bool:",
		"    if 'union' in spec:",
		"        return any(_validate_named(name, value) for name in spec['union'])",
		"    if isinstance(spec.get('type'), list):",
		"        return any(_validate_named(name, value) for name in spec['type'])",
		"    if spec.get('array'):",
		"        if not isinstance(value, list): return False",
		"        if 'minItems' in spec and len(value) < spec['minItems']: return False",
		"        if 'maxItems' in spec and len(value) > spec['maxItems']: return False",
		"        child = {k: v for k, v in spec.items() if k not in {'array', 'optional', 'minItems', 'maxItems'}}",
		"        return all(_validate_spec(child, item) for item in value)",
		"    if spec.get('map'):",
		"        if not isinstance(value, dict): return False",
		"        child = {k: v for k, v in spec.items() if k not in {'map', 'optional'}}",
		"        return all(_validate_spec(child, item) for item in value.values())",
		"    if 'const' in spec and value != spec['const']: return False",
		"    kind = spec.get('type')",
		"    if kind == 'json': valid = True",
		"    elif kind == 'string': valid = isinstance(value, str)",
		"    elif kind == 'number': valid = isinstance(value, (int, float)) and not isinstance(value, bool)",
		"    elif kind == 'integer': valid = isinstance(value, int) and not isinstance(value, bool)",
		"    elif kind == 'boolean': valid = isinstance(value, bool)",
		"    else: valid = _validate_named(kind, value)",
		"    if not valid: return False",
		"    if isinstance(value, str):",
		"        if 'minLength' in spec and len(value) < spec['minLength']: return False",
		"        if 'maxLength' in spec and len(value) > spec['maxLength']: return False",
		"    if isinstance(value, (int, float)) and not isinstance(value, bool):",
		"        if 'minimum' in spec and value < spec['minimum']: return False",
		"        if 'maximum' in spec and value > spec['maximum']: return False",
		"    return True",
		"",
		"def _validate_named(name: str, value: Any) -> bool:",
		"    enum = _PROTOCOL_IDL['enums'].get(name)",
		"    if enum is not None: return value in enum['values']",
		"    alias = _PROTOCOL_IDL['aliases'].get(name)",
		"    if alias is not None: return _validate_spec(alias, value)",
		"    if name == 'ContextRuntimeCall': return validate_runtime_call(value)",
		"    if name == 'ContextRuntimeResult':",
		"        return any(_validate_named(method['result'], value) for method in _PROTOCOL_IDL['methods'].values())",
		"    record = _PROTOCOL_IDL['records'].get(name)",
		"    if record is None or not isinstance(value, dict): return False",
		"    if any(key not in record['fields'] for key in value): return False",
		"    for field_name, field in record['fields'].items():",
		"        if field_name not in value:",
		"            if field.get('optional'): continue",
		"            return False",
		"        if not _validate_spec(field, value[field_name]): return False",
		"    return True",
		"",
		"def validate_runtime_call(value: Any) -> bool:",
		"    if not isinstance(value, dict) or set(value) != {'method', 'params'}: return False",
		"    method = _PROTOCOL_IDL['methods'].get(value.get('method'))",
		"    return method is not None and _validate_named(method['params'], value.get('params'))",
		"",
		"def validate_runtime_result(method_name: str, value: Any) -> bool:",
		"    method = _PROTOCOL_IDL['methods'].get(method_name)",
		"    return method is not None and _validate_named(method['result'], value)",
		"",
	);
	return `${lines.join("\n")}\n`;
}

function rustIdentifier(value) {
	const words = value
		.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
		.split(/[^A-Za-z0-9]+/)
		.filter(Boolean);
	let result = words
		.map((word) => word[0].toUpperCase() + word.slice(1).toLowerCase())
		.join("");
	if (/^[0-9]/.test(result)) result = `V${result}`;
	return result || "Value";
}

function rustField(value) {
	const snake = value
		.replace(/([a-z0-9])([A-Z])/g, "$1_$2")
		.replace(/[^A-Za-z0-9]+/g, "_")
		.toLowerCase();
	return ["type", "match", "ref", "self", "crate", "super"].includes(snake)
		? `r#${snake}`
		: snake;
}

function rustType(spec) {
	let type;
	if (spec.union) type = spec.union.join("Or");
	else if (Array.isArray(spec.type)) type = spec.type.join("Or");
	else if (spec.type === "string") type = "String";
	else if (spec.type === "number") type = "f64";
	else if (spec.type === "integer") type = "i64";
	else if (spec.type === "boolean") type = "bool";
	else if (spec.type === "json") type = "Value";
	else type = spec.type;
	if (spec.map) type = `BTreeMap<String, ${type}>`;
	if (spec.array) type = `Vec<${type}>`;
	return type;
}

function rustFloatLiteral(value) {
	return Number.isInteger(value) ? `${value}.0` : String(value);
}

function rustSpecExpression(spec, variable) {
	if (spec.union) {
		return `(${spec.union.map((name) => `validate_named(${json(name)}, ${variable})`).join(" || ")})`;
	}
	if (Array.isArray(spec.type)) {
		return `(${spec.type.map((name) => `validate_named(${json(name)}, ${variable})`).join(" || ")})`;
	}
	if (spec.array) {
		const child = fieldBase(spec);
		const checks = [];
		if (spec.minItems !== undefined) checks.push(`items.len() >= ${spec.minItems}`);
		if (spec.maxItems !== undefined) checks.push(`items.len() <= ${spec.maxItems}`);
		checks.push(`items.iter().all(|item| ${rustSpecExpression(child, "item")})`);
		return `${variable}.as_array().is_some_and(|items| ${checks.join(" && ")})`;
	}
	if (spec.map) {
		const child = fieldBase(spec);
		return `${variable}.as_object().is_some_and(|object| object.values().all(|item| ${rustSpecExpression(child, "item")}))`;
	}
	let base;
	if (spec.type === "json") base = "true";
	else if (spec.type === "string") base = `${variable}.as_str().is_some()`;
	else if (spec.type === "number") base = `${variable}.as_f64().is_some()`;
	else if (spec.type === "integer") {
		base = `(${variable}.as_i64().is_some() || ${variable}.as_u64().is_some())`;
	} else if (spec.type === "boolean") base = `${variable}.as_bool().is_some()`;
	else base = `validate_named(${json(spec.type)}, ${variable})`;
	const checks = [base];
	if (spec.const !== undefined) checks.push(`${variable} == &serde_json::json!(${json(spec.const)})`);
	if (spec.minLength !== undefined) {
		checks.push(`${variable}.as_str().is_some_and(|text| text.chars().count() >= ${spec.minLength})`);
	}
	if (spec.maxLength !== undefined) {
		checks.push(`${variable}.as_str().is_some_and(|text| text.chars().count() <= ${spec.maxLength})`);
	}
	if (spec.minimum !== undefined) {
		checks.push(
			`${variable}.as_f64().is_some_and(|number| number >= ${rustFloatLiteral(spec.minimum)})`,
		);
	}
	if (spec.maximum !== undefined) {
		checks.push(
			`${variable}.as_f64().is_some_and(|number| number <= ${rustFloatLiteral(spec.maximum)})`,
		);
	}
	return `(${checks.join(" && ")})`;
}

function generateRust() {
	const lines = [
		"// @generated by plugin/protocol/scripts/generate.mjs; DO NOT EDIT.",
		"#![allow(dead_code, unused_parens)]",
		"use serde::{Deserialize, Serialize};",
		"use serde_json::Value;",
		"use std::collections::BTreeMap;",
		"",
		`pub const PROTOCOL_VERSION: i64 = ${idl.version};`,
		`pub const PROTOCOL_IDL_SHA256: &str = ${json(idlSha256)};`,
		"",
	];
	for (const [name, definition] of Object.entries(idl.enums)) {
		lines.push(
			"#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
			`pub enum ${name} {`,
		);
		for (const value of definition.values) {
			lines.push(`    #[serde(rename = ${json(value)})]`, `    ${rustIdentifier(value)},`);
		}
		lines.push("}", "");
	}
	for (const [name, definition] of Object.entries(idl.aliases)) {
		if (definition.union) {
			lines.push(
				"#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
				"#[serde(untagged)]",
				`pub enum ${name} {`,
			);
			for (const variant of definition.union) {
				lines.push(`    ${variant}(${variant}),`);
			}
			lines.push("}", "");
		} else {
			lines.push(`pub type ${name} = ${rustType(definition)};`, "");
		}
	}
	for (const [name, definition] of Object.entries(idl.records)) {
		lines.push(
			"#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
			"#[serde(deny_unknown_fields)]",
			`pub struct ${name} {`,
		);
		for (const [fieldName, field] of Object.entries(definition.fields)) {
			const rustName = rustField(fieldName);
			if (rustName.replace("r#", "") !== fieldName) {
				lines.push(`    #[serde(rename = ${json(fieldName)})]`);
			}
			if (field.optional) {
				lines.push("    #[serde(default, skip_serializing_if = \"Option::is_none\")] ");
			}
			lines.push(`    pub ${rustName}: ${field.optional ? `Option<${rustType(field)}>` : rustType(field)},`);
		}
		lines.push("}", "");
	}
	lines.push(
		"#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
		"#[serde(tag = \"method\", content = \"params\")]",
		"pub enum ContextRuntimeCall {",
	);
	for (const [method, definition] of Object.entries(idl.methods)) {
		lines.push(
			`    #[serde(rename = ${json(method)})]`,
			`    ${rustIdentifier(method)}(${definition.params}),`,
		);
	}
	lines.push(
		"}",
		"",
		"#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
		"#[serde(untagged)]",
		"pub enum ContextRuntimeResult {",
	);
	for (const resultName of new Set(
		Object.values(idl.methods).map((definition) => definition.result),
	)) {
		lines.push(`    ${resultName}(${resultName}),`);
	}
	lines.push("}", "", "fn validate_named(name: &str, value: &Value) -> bool {", "    match name {");
	for (const [name, definition] of Object.entries(idl.enums)) {
		lines.push(
			`        ${json(name)} => value.as_str().is_some_and(|item| matches!(item, ${definition.values.map(json).join(" | ")})),`,
		);
	}
	for (const [name, definition] of Object.entries(idl.aliases)) {
		lines.push(`        ${json(name)} => ${rustSpecExpression(definition, "value")},`);
	}
	lines.push(
		"        \"ContextRuntimeCall\" => validate_runtime_call(value),",
		`        "ContextRuntimeResult" => ${[
			...new Set(Object.values(idl.methods).map((definition) => definition.result)),
		].map((name) => `validate_named(${json(name)}, value)`).join(" || ")},`,
	);
	for (const [name, definition] of Object.entries(idl.records)) {
		const allowed = Object.keys(definition.fields)
			.map(json)
			.join(" | ");
		const fieldChecks = [];
		for (const [fieldName, field] of Object.entries(definition.fields)) {
			const expression = rustSpecExpression(field, "field");
			fieldChecks.push(
				field.optional
					? `object.get(${json(fieldName)}).is_none_or(|field| ${expression})`
					: `object.get(${json(fieldName)}).is_some_and(|field| ${expression})`,
			);
		}
		lines.push(
			`        ${json(name)} => value.as_object().is_some_and(|object| {`,
			`            object.keys().all(|key| matches!(key.as_str(), ${allowed}))`,
			`                && ${fieldChecks.join("\n                && ")}`,
			"        }),",
		);
	}
	lines.push(
		"        _ => false,",
		"    }",
		"}",
		"",
		"pub fn validate_runtime_call(value: &Value) -> bool {",
		"    let Some(object) = value.as_object() else { return false; };",
		"    if object.len() != 2 { return false; }",
		"    let (Some(method), Some(params)) = (object.get(\"method\").and_then(Value::as_str), object.get(\"params\")) else { return false; };",
		"    match method {",
	);
	for (const [method, definition] of Object.entries(idl.methods)) {
		lines.push(`        ${json(method)} => validate_named(${json(definition.params)}, params),`);
	}
	lines.push(
		"        _ => false,",
		"    }",
		"}",
		"",
		"pub fn validate_runtime_result(method: &str, value: &Value) -> bool {",
		"    match method {",
	);
	for (const [method, definition] of Object.entries(idl.methods)) {
		lines.push(`        ${json(method)} => validate_named(${json(definition.result)}, value),`);
	}
	lines.push("        _ => false,", "    }", "}", "");
	return `${lines.join("\n")}\n`;
}

const schema = buildSchema();
const schemaText = `${JSON.stringify(schema, null, 2)}\n`;
const schemaSha256 = createHash("sha256").update(schemaText).digest("hex");
const pythonBindings = generatePython();
const outputs = new Map([
	[resolve(protocolRoot, "schema/magic-context.schema.json"), schemaText],
	[resolve(protocolRoot, "src/generated.ts"), generateTypeScript()],
	[
		resolve(protocolRoot, "generated/python/magic_context_protocol.py"),
		pythonBindings,
	],
	[
		resolve(repositoryRoot, "plugin/hermes-plugin/generated_protocol.py"),
		pythonBindings,
	],
	[resolve(protocolRoot, "generated/rust/protocol.rs"), generateRust()],
	[
		resolve(protocolRoot, "generated/manifest.json"),
		`${JSON.stringify(
			{
				protocolVersion: idl.version,
				idlSha256,
				schemaSha256,
				methods: idl.methods,
			},
			null,
			2,
		)}\n`,
	],
]);

let stale = false;
for (const [path, content] of outputs) {
	if (checkOnly) {
		const current = await readFile(path, "utf8").catch(() => undefined);
		if (current !== content) {
			process.stderr.write(`generated protocol file is stale: ${path}\n`);
			stale = true;
		}
	} else {
		await writeFile(path, content, "utf8");
		process.stdout.write(`generated ${path}\n`);
	}
}
if (stale) process.exitCode = 1;
